name: Publish

on:
  workflow_dispatch:
  push:
    tags:
      - "*"

jobs:
  publish-all:
    name: Publish all packages
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    environment:
      name: production
      url: ${{ steps.gh-release.outputs.url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Release data
        id: get_release_data
        if: github.ref_type == 'tag'
        run: |
          MESSAGE=$(git tag -l --format='%(contents)' "${GITHUB_REF_NAME}")
          echo "$MESSAGE" >> release-message.txt
          cat release-message.txt

          NPM_TAG="latest"
          if [[ "${GITHUB_REF_NAME}" == *-* ]]; then
            NPM_TAG="next"
          fi
          echo "NPM_TAG=${NPM_TAG}" >> $GITHUB_ENV
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: Setup Turbo
        id: setup
        run: |
          pkgNames=()
          pkgDirs=($(ls -d ./packages/*/))
          for i in "${pkgDirs[@]}"; do
            dirname=$(basename "$i")
            if [ "$dirname" == "cli" ]; then
              continue
            else 
              pkgNames+=("@storybooker/$dirname")
            fi  
          done

          npx -y turbo prune storybooker ${pkgNames[@]}           
          cp tsconfig.base.json out/tsconfig.base.json
          cp .oxlintrc.json out/.oxlintrc.json
          cp -R scripts out/scripts

      - name: Install dependencies
        working-directory: ./out
        run: yarn install --immutable
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

      - name: Verify
        working-directory: ./out
        run: npx turbo verify

      - name: Create GitHub Release
        if: github.ref_type == 'tag'
        id: gh-release
        uses: softprops/action-gh-release@v2
        with:
          body_path: release-message.txt
          make_latest: ${{ steps.get_release_data.outputs.NPM_TAG == 'latest' }}

      - name: Publish on JSR - Core
        working-directory: ./out/packages/core
        continue-on-error: true
        run: npx -y jsr publish --token ${{ secrets.JSR_API_TOKEN }} --allow-slow-types

      - name: Publish on NPM
        working-directory: ./out
        run: |
          NPM_TAG="${{ steps.get_release_data.outputs.NPM_TAG || 'latest' }}"
          yarn workspaces foreach -A --no-private npm publish --tolerate-republish --tag $NPM_TAG
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
